@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 23 20:54:46 -0700 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test1_tb_func_synth -key {Post-Synthesis:sim_1:Functional:test1_tb} -tclbatch test1_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Lab4/Lab4Verilog/test1_tb_behav.wcfg -log simulate.log"
call xsim  test1_tb_func_synth -key {Post-Synthesis:sim_1:Functional:test1_tb} -tclbatch test1_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Lab4/Lab4Verilog/test1_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
