@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Dec 02 03:19:41 -0700 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim comp_top_tb_func_synth -key {Post-Synthesis:sim_1:Functional:comp_top_tb} -tclbatch comp_top_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Competition/CompetitionVerilog/comp_top_tb_behav.wcfg -log simulate.log"
call xsim  comp_top_tb_func_synth -key {Post-Synthesis:sim_1:Functional:comp_top_tb} -tclbatch comp_top_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Competition/CompetitionVerilog/comp_top_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
