@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 12 13:56:36 -0700 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim lab6_waveform_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab6_waveform_tb} -tclbatch lab6_waveform_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Lab6/Lab6Verilog/lab6_waveform_tb_behav.wcfg -log simulate.log"
call xsim  lab6_waveform_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab6_waveform_tb} -tclbatch lab6_waveform_tb.tcl -view C:/Users/alexr/Documents/Projects/ECE-369/Lab6/Lab6Verilog/lab6_waveform_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
